FROM ubuntu:14.04

RUN apt-get update && apt-get install -q -y build-essential \
    git-core \
    pkg-config \
    automake \
    libtool \
    wget \
    zlib1g-dev \
    python-dev \
    libbz2-dev

RUN useradd --user-group --create-home --shell /bin/false moses

ENV HOME=/home/moses

ENV BIN_HOME=$HOME/bin
ENV MOSES_HOME=$BIN_HOME/moses

WORKDIR $MOSES_HOME
RUN chown -R moses:moses $HOME

USER moses

# Build uses multiple cores if available, but this requires
# extra RAM (4 cores: 2 GB)
RUN git clone --depth 1 https://github.com/moses-smt/mosesdecoder.git \
    && cd mosesdecoder \
    && make -f contrib/Makefiles/install-dependencies.gmake \
       PREFIX=${BIN_HOME}/opt \
    && OPT=${BIN_HOME}/opt ./compile.sh --prefix=${MOSES_HOME} \
       --install-scripts \
    && cd - \
    && rm -rf mosesdecoder

RUN git clone --depth 1 https://github.com/moses-smt/giza-pp.git \
    && cd giza-pp \
    && make \
    && mkdir ${BIN_HOME}/tools \
    && cp GIZA++-v2/GIZA++ GIZA++-v2/snt2cooc.out mkcls-v2/mkcls \
       ${BIN_HOME}/tools \
    && cd - \
    && rm -rf giza-pp

ENV LD_LIBRARY_PATH $BIN_HOME/opt/lib
